# Use root/password as user/password credentials
version: "3.1"

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: JobList
    networks:
      - BackendNetwork
    volumes:
      - type: bind
        source: ./docker-entrypoint-initdb.d
        target: /docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  # general structure for backend API was inspired by:
  # https://github.com/madhurajayashanka/docker-mysql-nodejs-reactjs-app/
  api:
    restart: always
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    networks:
      - BackendNetwork
    depends_on:
      - db

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - BackendNetwork
    depends_on:
      - api

  adminer:
    image: adminer
    restart: always
    networks:
      - BackendNetwork
    ports:
      - 8080:8080

networks:
  BackendNetwork: # Defines the 'sameNetworkAsMysql' network
    driver: bridge # Specifies the network driver as 'bridge'
