# Use root/password as user/password credentials
version: "3.1"

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: JobList
    volumes:
      - type: bind
        source: ./docker-entrypoint-initdb.d
        target: /docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
